### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### product index
GET http://localhost:3000/products.json

### product create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "product_name": "mocha powder",
  "description": "beverage component",
  "on_hand": 7,
  "Uom": 6
}

### show action
GET http://localhost:3000/products/1.json

### update action
PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
  "Uom": 4
}