### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### product index
GET http://localhost:3000/products.json

### product create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "product_name": "mocha powder",
  "description": "beverage component",
  "on_hand": 7,
  "Uom": 6
}

### show action
GET http://localhost:3000/products/1.json

### update action
PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
  "Uom": 4
}

### destroy action
DELETE http://localhost:3000/products/1.json

### order create
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "date_placed": "2023-09-02",
  "user_id": 1,
  "date_received": "2023-09-03",
  "products": [
    {
      "product_id": 1,
      "quantity_shipped": 4
    },
    {
      "product_id": 2,
      "quantity_shipped": 6
    },
    {
      "product_id": 3,
      "quantity_shipped": 3
    }
  ]
}

### order index
GET http://localhost:3000/orders.json

### order update action
PATCH http://localhost:3000/orders/1.json
Content-Type: application/json

{
  "date_received": "2023-09-03"
}

### product_order create
POST http://localhost:3000/product_orders.json
Content-Type: application/json

{
  "product_id": 2,
  "order_id": 1,
  "quantity_shipped": 12,
  "quantity_received": 10
}

### product_order update action
PATCH http://localhost:3000/product_orders/1.json
Content-Type: application/json

{
  "quantity_received": 4
}

### daily_usage create
POST http://localhost:3000/daily_usages.json
Content-Type: application/json

{
  "product_id": 2,
  "quantity_used": 4,
  "quantity_projected": 6,
  "date": "2023-09-03"
}

### daily_usage update action
PATCH http://localhost:3000/daily_usages/1.json
Content-Type: application/json

{
  "quantity_used": 4
}